CREATE DATABASE olymp;
USE olymp;
CREATE TABLE UserApp
(
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL
);
CREATE TABLE Task
(
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL
);
CREATE TABLE Test
(
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TaskId INT NOT NULL,
    InputData TEXT NOT NULL,
    OutputData TEXT NOT NULL
);
CREATE TABLE Submission
(
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TaskId INT NOT NULL,
    UserId INT NOT NULL
);
CREATE TABLE TasksForUser
(
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
    TaskId INT NOT NULL,
    UserId INT NOT NULL
);
ALTER TABLE Test ADD FOREIGN KEY (TaskId) REFERENCES Task (Id);
ALTER TABLE Submission ADD FOREIGN KEY (TaskId) REFERENCES Task (Id);
ALTER TABLE TasksForUser ADD FOREIGN KEY (TaskId) REFERENCES Task (Id);
ALTER TABLE Submission ADD FOREIGN KEY (UserId) REFERENCES UserApp (Id);
ALTER TABLE TasksForUser ADD FOREIGN KEY (UserId) REFERENCES UserApp (Id);